### ISSUE TITLE
Navbar and body links are different

### ISSUE THREAD

**Issue by ju-sh** [toml-lang/toml.io#14]
In the page for the 1.0.0.-rc.1 version (https://toml.io/en/v1.0.0-rc.1), under 'Key-Value pair', the links to the types (like string, integer, etc) do not lead to the corresponding content.

But the links in the navigation pane on the left leads to the content.

The hrefs in the links of navigation pane have 'section-<number>' in them and the links under 'Key-Value pair' has 'user-content-<topic>'.

And which static site generator is used for the website?

**Comment by cannikin** [comment]
Fixed! This was due to the specs assuming they were going be displayed in GitHub's README-markdown-to-HTML format so they included a prefixed "user-content" on each anchor (which GH inserts for linking to other parts of the README).

The generator is a really simple framework I built, [CameronJS](https://cameronjs.com/). The build script that converts markdown to HTML is custom in this case.

**Comment by garazdawi** [comment]
The same problem exists in the rc2 documentation.

**Comment by cannikin** [comment]
@garazdawi This should be fixed!

**Comment by pradyunsg** [comment]
Argh, I guess we should do this transform as part of the release process, i.e. in https://github.com/toml-lang/toml/blob/master/scripts/release.py.
