### ISSUE TITLE
Internal links are broken

### ISSUE THREAD

**Issue by eric-unc** [toml-lang/toml.io#29]
On [toml.io/en/v1.0.0-rc.3](https://toml.io/en/v1.0.0-rc.3), go to, say, the part that says "Naming rules for tables are the same as for keys (see definition of Keys above)." The _Keys_ is a link that is supposed to link to the Keys section. However, it does not. It links to `https://toml.io/en/v1.0.0-rc.3#user-content-keys` but that doesn't go anywhere. It should link to `https://toml.io/en/v1.0.0-rc.3#keys`.

I don't know how this web stack works at all so I figured I would make an issue rather than try to fix it myself. It's very weird that the table of contents uses links that end with (for example) `#user-content-keys` and it works perfectly fine, but using that outside of the ToC is clearly not working.

**Comment by cannikin** [comment]
Ahh, that's a remnant of how GitHub automatically links to anchors within a markdown document. Anything that's a header gets an anchor tag with the text in the header, but prefixed with `user-content-` so if you wanted to link to one of those headers internally within the markdown you needed to reference that same `user-content-` anchor.

When the specs were living at https://github.com/toml-lang/toml it was fine because everything was being viewed on GitHub. Now that they're moved over to https://github.com/toml-lang/toml.io/tree/main/specs we don't need the `user-content-` prefixes. I removed them from all of the other spec versions but didn't check whether rc3 had them or not.

It's an easy fix, will update in a minute.
