### ISSUE TITLE
Specification breaks at certain window widths/zoom levels

### ISSUE THREAD

**Issue by arp242** [toml-lang/toml.io#74]
For example at 140% I get a horizontal scrollbar:

![cap-2023-09-28T13:13:24_border](https://github.com/toml-lang/toml.io/assets/1032692/afe34242-51b0-4e9b-ad1d-8c5f8953099b)

Which gets even worse if you click a menu item, because it scrolls to the right:

![cap-2023-09-28T13:13:35_border](https://github.com/toml-lang/toml.io/assets/1032692/03103b0c-e2be-4d66-bba9-3549b411c762)

At ~160% the mobile nav kicks in.

The exact values differ a bit per system, depending on screen resolution, window size, screen scaling, etc. You can also reproduce it by just making the window smaller, but the main gist is: there are some width that don't work well.

It should really just make the main content smaller; the reason it doesn't is because some wide pre tags make it larger. `pre { max-width: calc(100vw - 21rem); }` fixes it, but there's probably a better way.

**Comment by arp242** [comment]
@cannikin How attached are you to Tailwind? Is "remove Tailwind and replace it with more basic CSS" an option for you?

That Tailwind thing is, IMHO hugely over-complex for this, and to be honest it almost seems easier for me to just re-do the CSS than fix it inside the Tailwind framework. That would also make future changes easier, I think?

I don't really want to argue tech choices, so just "yes" or "no" is fine.

**Comment by cannikin** [comment]
I'd want to keep Tailwind myself—I spent the first 20 years of my career writing CSS manually, and I can't go back now! Tailwind itself is pretty bulletproof, I bet I'm just missing a style somewhere.

I've seen that seemingly fixed-width `<pre>` layout bug on another project—I had to find the proper combination of `overflow-auto` on the parent containers in order to fix it. 

**Edit** I just did a quick test and adding `overflow-auto` to the `<main>` tag makes the `<pre>` behave itself (at least during the quick test I did). How does it look to you?

**Comment by arp242** [comment]
Right so. Like I said, I don't really want to discuss tech choices as I feel that would be a waste of both our time. Just wanted to see what the options are.

I tried a bunch of things before I reported this issue; I'll take another look.

**Comment by cannikin** [comment]
Did you try my **Edit** from above? That seemed to fix it before the breakpoint kicked in (on Chrome and Safari on macOS, at least).

**Comment by cannikin** [comment]
I just committed that change, looks good to me! I'm gonna close this, but re-open if something still seems wonky...

**Comment by arp242** [comment]
> Did you try my Edit from above?

No, I didn't – was just a general comment.

Tested and seems grand now :+1:
